### ISSUE TITLE
Footer fonts are too big

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/puppylinux-woof-CE.github.io#11]
Not sure if this was always the case but the footer fonts are too big. Looks bigger than the rest of the text.  Would be better to be at least one size smaller. Maybe 2.

**Comment by 01micko** [comment]
Well they _should_ be same size (appear so to me in gecko and blink) but dunno about webkit. Can easy make them smaller in puppy.css - puppy-bar-bg.

Add `font-size: 0.8em;`

**Comment by 01micko** [comment]
I added the css and am closing but re-open if it's no good for you.

**Comment by mavrothal** [comment]
Looks fine
