### ISSUE TITLE
Should we delete 'in_progress'

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/puppylinux-woof-CE.github.io#12]
As title says or should we keep it as a "playground"?

**Comment by mavrothal** [comment]
I was wondering if we rename (or delete and make a new one) "in_progress" to "publish" and put the redirect there. So changes, pulls, etc in "master" can be reviewed in puppylinux-woof-CE.github.io and if happy merge to "publish" to be shown in the official "puppylinux.com". Not sure if github allows redirect from other branches though. If it does I would go for it.
If not we could keep "in_progress" and ask people to issue pull request for this branch so we can have the chance to review them at least locally, before "publishing" by merging to master.

**Comment by 01micko** [comment]
hmmm.. what I could do if github does not allow ..

>  Not sure if github allows redirect from other branches though. If it does I would go for it.

..is create a subdomain at eezy.xyz for testing, which _should_ work with the CNAME file (or something similar). I suppose we would have to read the docs or ask a question to be certain.

**Comment by mavrothal** [comment]
Or just try :wink: 
Merge, do a change (smething like "more to come" at the bottom in the index.html or elsewhere) in "in_progress" and see if is published

**Comment by 01micko** [comment]
Yeah.. tomorrow or something! Had enough today.

**Comment by mavrothal** [comment]
Maybe I'll try it.
Is still early here.
Did you announce it?
Bummer. You did. Still... :smiling_imp:

**Comment by 01micko** [comment]
I just pushed 'in_progress' then took out `CNAME` to avoid conflict.

**Comment by mavrothal** [comment]
> Maybe I'll try it.

Tried it. Does not work. 
Github redirects only from the master branch.
So changes in another branch can be viewed only locally :disappointed:

**Comment by 01micko** [comment]
may as well delete it, fairly useless IMHO.

**Comment by mavrothal** [comment]
> may as well delete it, fairly useless IMHO

The only issue is that if we have only master we can only review changes from pulls after they are published. With in-progress we can pull sync and check locally.
gh-pages as James suggested would be better but I'm not sure if github allows to have remote branch in another repo or all this should be done locally as described [here](http://stackoverflow.com/questions/21353656/merge-git-repo-into-branch-of-another-repo)

**Comment by 01micko** [comment]
Ok because of [closing `gh-pages`](https://github.com/puppylinux-woof-CE/woof-CE/issues/754#issuecomment-191160828) this issue is resolved; that is we keep `in_progress`.
