### ISSUE TITLE
Wow! We are live!

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/puppylinux-woof-CE.github.io#13]
Check it out!

[puppylinux.com](http://puppylinux.com)

I didn't have to delete cache or anything, just straight away works. Now to test links from woof and such.

**Comment by mavrothal** [comment]
Congrats! 
woof has faq.htm not html. Either redirect to BK's (the file in gh-pages) or link to faq.html. Though faq.htm is mostly technical so a redirect might be better for now

**Comment by 01micko** [comment]
I prefer option 2. Calling it a day after that.

**Comment by 01micko** [comment]
Closing as not really an issue but we can still comment anyway!

**Comment by jamesbond3142** [comment]
Congrats Mick, Mav!

**Comment by mavrothal** [comment]
If I remember correctly was **you** that started it and also  added a lot of the current content, so congratulations to you!

**Comment by 01micko** [comment]
> If I remember correctly was you that started it and also added a lot of the current content, so congratulations to you!

:+1:
