### ISSUE TITLE
Do we want to stay "grandpa-friendly certified"

### ISSUE THREAD

**Issue by L18L** [puppylinux-woof-CE/puppylinux-woof-CE.github.io#19]
A grandpa on puppy forum wrote:

> Now that I can admire the page, without firing-up more modern boxen with more recent Pups, perhaps I could offer a positive suggestion? - - even on a big screen, the text contrast seems a tad suboptimal to me (as in, strong grey on weak grey background) - might it not be an advantage, especially for those visiting with smallscreen devices/low batteries, to have just plain ol' black-on-white for the text content?

Grandpas like black-on-white.
Grandpas need black-on-white.
Grandpas are used to black-on-white.

In the time of using recycled paper this might also become black-on-lightyellow.
It is just changing css for body
`body {color:black;background:lightyellow;}`

AND / OR let user choose alternate stylesheet, W3.org is teaching how to make it: https://www.w3.org/Style/Examples/007/alternatives.en.html

Thus simply add

```
  <link rel="alternate stylesheet" title="Grand Pa" href="<path-to>/grandpa.css">
  <link rel="alternate stylesheet" title="Kid" href="<path-to>/kid.css">
```

into head of source

and create two stylesheets
grandpa.css:
`body {color:black;background:lightyellow;}`
kid.css:
`body {color:white;background:black;}`

Regards from a grandpa

**Comment by L18L** [comment]
Here is how it might look

deleted and uploaded another image

![new_page_puppy_linux_grandpa-friendly](https://cloud.githubusercontent.com/assets/6724772/13555285/9da84b32-e3bc-11e5-813e-1e56838824fb.png)

**Comment by jamesbond3142** [comment]
I certainly am okay with that. I'm just curious why mavrothal nick is shown more than a dozen times in your screenshots :fearful:

**Comment by L18L** [comment]
> I certainly am okay with that. I'm just curious why mavrothal nick is shown more than a dozen times in your screenshots

 I just wanted to see the clutter (super long string of contributors). 
And - as I am slow and lazy - simply copied last nick and copied and copied.....
Sorry, copied another string and image, though.

**Comment by 01micko** [comment]
This would be even better if it were persistent across pages. Any way to do that?

Now, if I set 'grandpa' or 'kids' it only sticks to that page and if I navigate to say 'screenshots' it goes back to default. Maybe there is an extension?

**Comment by 01micko** [comment]
Ok, there is an alternative but everyone with _js_ disabled will cop it.

Contrary to popular belief _noscript_ tag _is_ allowed in `<head>` ([ref](http://www.w3.org/TR/html4/strict.dtd)). So simply calling `grandpa.css` inside the `<noscript>` tags works.

I think most people browse with _js_ enabled so won't affect too many, and those it does probably won't care too much anyway.

**Comment by L18L** [comment]
> This would be even better if it were persistent across pages. Any way to do that?

The usual way:  Refresh (Reload) the page.

> Contrary to popular belief noscript tag is allowed in <head> (ref). 

Sorry, why ref to html4 from 1999 ? html is html5 now

---

Some grandpas, grandmas, mamas and papas have javascript enabled and would like to read black-on-white (or any other additional alternate style).

**Comment by 01micko** [comment]
Well, issue a pull request!

But.... what would be better if we could make use of the several themes in `v/bootstrap/2.1`. There is js out there to switch themes.
