### ISSUE TITLE
Top banner is covering text in older webkit browsers

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/puppylinux-woof-CE.github.io#20]
As the title says. 
Browser: google chrome 33, epiphany 3.8.1, qtweb, 3.8.4. circa 2013-14. 
OS: puppy precise 5.5, Fedora 18.
Is also very bad with dillo but that's because it hardly support css.

**Comment by 01micko** [comment]
This should get reasonably fixed when I convert the navbar back to a table (improved version). So far I've tested in IE6, SM-1.1.18, new browsers (including safari), current qupzilla, konqeror and netsurf and it's fine. Converting the icons to PNG helps with older browsers too.

It might take me a while though as my main box' power supply died and a new one might take a while to arrive.

**Comment by mavrothal** [comment]
Yeap. 1bd9a21 did it
