### ISSUE TITLE
Is there any specific reasons to use `<table></table>`  tags in navigation bar ?

### ISSUE THREAD

**Issue by Mr-Kumar-Abhishek** [puppylinux-woof-CE/puppylinux-woof-CE.github.io#23]
I was looking over the design and found out that there were use of `<table></table>` tags in navigation bar. Use `<table></table>` tags for design purposes is not recommended anymore. (It was done in past though). Search engines don't read much whatever is in `<table></table>` tags as they are meant for data, such as done for download links for various flavors of Puppy Linux  in this website. I don't think changing them to use `<ul></ul>`,`<li></li>` and `<nav></nav>`
tags and then keeping the same design with the help some more CSS will raise any complexity in contribution.

The only reason of keeping `<table></table>` I could think of is better look in console browsers such as [lynx](http://lynx.browser.org/)

If it is okay I will include them with my current [pull request](https://github.com/puppylinux-woof-CE/puppylinux-woof-CE.github.io/pull/22) or should I do this in another pull request ?

**Comment by 01micko** [comment]
I'm about to merge your current PR so please create a new one. Thanks :smile:

**Comment by Mr-Kumar-Abhishek** [comment]
Alright  :relaxed:
