### ISSUE TITLE
http://librepup.info/ has expired

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/puppylinux-woof-CE.github.io#25]
table  puppylinux-woof-CE.github.io/download.md

on  http://puppylinux.com/download.html

NOTICE: This domain name expired on 9/14/2016 and is pending renewal or deletion.

for  http://librepup.info/

**Comment by Mr-Kumar-Abhishek** [comment]
I have removed the link with my pull request, this would probably sort things out  :jack_o_lantern:
