### ISSUE TITLE
Use HTTPS for the website and download links

### ISSUE THREAD

**Issue by dhouck** [puppylinux-woof-CE/puppylinux-woof-CE.github.io#34]
Github Pages supports HTTPS even when using a custom domain; see [here](https://help.github.com/en/articles/securing-your-github-pages-site-with-https) for more info. Ibiblio also supports HTTPS and you can just change the http:// links to https:// and things should work.

You should use HTTPS pretty much everywhere, *especially* when downloading programs to run on the computer, and *certainly* when downloading operating systems.

**Comment by 01micko** [comment]
Thanks for the tip but I have to _pay_ for https on my hosting. Doesn't support _let's encrypt_. Yes I am considering moving.

![github](https://user-images.githubusercontent.com/1019119/58378219-cf0be100-7fd3-11e9-91c3-8531839178a5.jpg)


Thanks for the tip about ibiblio too. We should adjust the links on the download page.

**Comment by dhouck** [comment]
Interesting; I thought from the GitHub docs that if you have the A and AAAA records set to point to GitHub can (for free) handle setting up Let's Encrypt without anything else. What's the part that you need to pay for?
