### ISSUE TITLE
Forum links

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/puppylinux-woof-CE.github.io#36]
July 2020
With the very sad demise of John de Murga and with him the demise of the murgalinux puppy forum, there are many links on the puppylinux.com website that are now disfunctional.......

**Comment by peabee** [comment]
@01micko - thanks for doing the hopefully "interim" change to the page menus........
Perhaps pages like the download page with many murga forum links should just have a warning that the links do not work - for now?

**Comment by 01micko** [comment]
@peabee this all should be resolved now. All that needs doing is adding a link to oldforum.puppylinux.com and changing the 'main' forum link to forum.puppylinux.com which is out of scope for this issue so I'll close.
