### ISSUE TITLE
Precise is missing from history

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/puppylinux-woof-CE.github.io#4]
Precise should be in the 5.x puppies.  Was it the newest in the 5.x or was it before wary/racy?

**Comment by 01micko** [comment]
Wary/racy (5.1.1 - wary, 5.2.2 - racy)  preceded Precise (5.4) as in the timeline graphic. While graphic isn't precise at all ( :tongue: ) it is pretty close to being in correct chronological order.

I'll add some blurb for Precise.
