### ISSUE TITLE
the listing of the Puppy versions is confussing to people.

### ISSUE THREAD

**Issue by bigpup1** [puppylinux-woof-CE/puppylinux-woof-CE.github.io#53]
On main page of puppylinux.com where there is a list of Puppy versions that can be used.

They are listed in columns.
Compatibility column is first one and it has names in it that are the Linux OS a Puppy version is based on.
People posting on the forum are using these for the Puppy version name.

The Puppy version names are in the 3rd column latest version.

Ned to switch the compatibility column with the latest version column.

So the first column is Latest Version and is giving the Puppy version name, 

So when people look at this list it reads to them:
This is the Puppy version.
This is the architecture.
This is the compatible Linux OS
This is the download links.

**Comment by peabee** [comment]
Done
