### ISSUE TITLE
Add "last updated" automatically

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/puppylinux-woof-CE.github.io#7]
I can see searching the web that there javescripts automatically [adding](http://www.boogiejack.com/last_updated.html) "last update" in the pages. 
can we change to default page layout to add a footer with this?

Another cool thing (I think) would if we could have a popup that will show the contributors in a page as determined by the commit messages affecting the given page. Might encourage contributions by people that would like a more visible acknowledgment/recognition.
`git log --follow path/filename` or just `git log  path/filename` and grep'ing for `^Author` will provide this info but how you het javascript to generate the relevant popups automatically I have no idea.

**Comment by mavrothal** [comment]
BTW I use this little script to do that in my repos

```
#!/bin/sh
WD=$(pwd)
[ ! -d ${WD}/.git ] && echo This is not the root of a git repo. Exiting && exit 1
echo "" > author_list
for f in $(find . -type f | grep -v \/\.git\/ | grep -v author_list | cut -f 2-20 -d '/')
do
    AUTHS=$(git log --follow $f | grep -i ^Author | cut -f 1 -d '<' | cut -f 2-4 -d ' ' | sort | uniq)
    echo "Path_n_File: ${f}" >> author_list
    echo "${AUTHS}" >> author_list
    echo "" >> author_list
done

```

**Comment by 01micko** [comment]
``` js
// script from BoogieJack.com - modified somewhat
var x = new Date(document.lastModified);
var m = "<strong>Puppy Linux Team © 2016</strong> - Page Last Updated " + x;
var p = m.length-8;
document.writeln("<div class='container puppy-bar-bg'>");
document.write(m.substring(p, 0));
document.writeln("</div>");
```

Add that to `puppy.js` (I put it as the second last one) and comment out the `//load header and footer` block.

Works! So definitely do-able.

I have NO idea if the syntax is legal!

Your second request .. well might be a bit ambitious.

**Comment by mavrothal** [comment]
> Your second request .. well might be a bit ambitious.

Maybe poke techno? :wink:

**Comment by 01micko** [comment]
Just a note about the above js code.

`var p = m.length-8` isn't suitable in my hack. It should either be the full `m.length` which basically prints the full time, with GMT offset and timezone or `m.length-24` which chops it off at the year.

eg

> **Puppy Linux Team © 2016** - Page Last Updated Tue Mar 01 2016 14:50:17 GMT+1000 (AEST)

or

> **Puppy Linux Team © 2016** - Page Last Updated Tue Mar 01 2016

What is better? Personally I'd rather option 2, especially if browsing on a phone.

**Comment by mavrothal** [comment]
Looks like the contributors insertion [might be doable](http://www.htmlhelp.com/faq/html/design.html#include-file) though is for whole files.
Alternatively in your script above, may replace (or add) "Puppy Linux Team © 2016" with "page contributors: this, that, theother" and have a script running automatically every day to update the "this, that, theother" field

> What is better?

Option 2!

**Comment by jamesbond3142** [comment]
I'll add that last modified thing. Syntax is legal although document.writeln is ancient. Contributors list - as long as the info can be pulled there somewhere, programmatically, it is possible. I know that github has API of sorts for integration purposes, but I've never explored that.

**Comment by mavrothal** [comment]
> Syntax is legal although document.writeln is ancient

The relevant google search got results earlier in the page but this was a first page result I could understand a bit :blush:

**Comment by jamesbond3142** [comment]
hehehe... if you don't like the date format, in puppy.js, instead of 

``` javascript
$("#last-updated").html(d);
```

you can change that to 

``` javascript
$("#last-updated").html(d.toString());
```

or

``` javascript
$("#last-updated").html(d.toDateString());
```

or

``` javascript
$("#last-updated").html(d.toUTCString());
```

But I choose the first one because I'm not sure whether the other ones are supported by Infernal Exploder.

**Comment by jamesbond3142** [comment]
page contributor names now automatically pulled from github.com.

**Comment by mavrothal** [comment]
Cool!
Is there any way to make it a popup?
With 2-3 contributors things are simple but if the list  expands (wishful thinking :tongue: ) is going to start looking strange.
I also  find showing the _exact time_ of last update a bit of overkill for a (mostly) static web page.
Anyway, I'll close this just the same.

Maybe is time to get this page live.

**Comment by jamesbond3142** [comment]
Yup, I shortened it by using toDateString() - but not sure if other browsers support it (notably IE). We'll leave it at that for the moment. String manipulation like Mick did is also possible.

As for popup, yeah that's certainly possible ... the problem is, there is no "mouse-over" function on mobiles, so it must be some sort of a click/tap. I'll leave that to Mick :smiling_imp: May be a menu item to show "page info" of sorts?

**Comment by jamesbond3142** [comment]
Note: the order given in the "contributors" list is the order or latest commit. Currently it shows my name first because I just updated all of the pages (remove the manual "last update" text); but as soon as you, Mick, or anyone else update the page, their names will be shown first.

**Comment by 01micko** [comment]
I think the top menu is full enough :smirk_cat: .. especially on my 4.3" phone. Any smaller res and it does get a little ugly but I think 4.3 is pretty small these days. (I have a battery in the mail for my 3.7" phone so we'll see what happens when that arrives. IIRC its 720X460, so should be ok) 

> Note: the order given in the "contributors" list is the order or latest commit. 

That will level out in due course.

@mavrothal - another 'Parent' on the main page, how did we miss that? Anyway, since james has settled I'll push it with just 'Compatibility' as to not stretch out the table too much.

Anyway, after the `arch.html` page is populated I think we're ready to go live.
