### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by jamesbond3142** [puppylinux-woof-CE/puppylinux-woof-CE.github.io#9]
I think we need screenshots somewhere. 
The landing page could have one (just under the description of "About Puppy Linux", and perhaps there is a link to a dedicated screenshot page in the "more info" section, also in the first page.

I was about to do this myself and ~~steal~~ borrow some screenshots from slacko website, but it seems a bit barren. A shot that shows several applications open would be nice. Either from slacko or from tahrpup (both are officials) would be fine.

**Comment by 01micko** [comment]
Agreed. We need such a page.

**Comment by 01micko** [comment]
I think they have to be all consistent screen size, and lower res screen is better (say typical low range lappy @ 1366x768).

I have a little time tomorrow so I'll fire up them all on my old lappie and grab a few.

Here's my KDE mockup which I'm thinking of running with in the next Slacko... (res is too big tho)

![fff](https://cloud.githubusercontent.com/assets/1019119/13425818/08267626-dff5-11e5-8210-d8f896c6a755.png)

**Comment by mavrothal** [comment]
1366x768 is not a common aspect ratio. What about 1280X800 (1:1.6)?
A VM, should do the job.
LxPup and X-slacko may also be good to have, as an alt desktop. Make a folder and I may upload some to choose from (an delete the rest)

**Comment by 01micko** [comment]
Well, I couldn't get a nice res in a VM! So I booted a USB key on my intel box hooked up to TV (1080p - same one I use for Fatdog-Arm) and decreased dimensions by half in mtpaint - 1365*768 :laughing: It looks ok. I'll commit shortly.

> LxPup and X-slacko may also be good to have, as an alt desktop.

Included.

**Comment by 01micko** [comment]
Feel free to edit as you see fit.

**Comment by mavrothal** [comment]
Looks nice though I would probably had the "advantages" first and then after the "read on" and to keep/start the cheeky mood, add the image under the title "Yes, but what does it look like? :smile_cat:

**Comment by mavrothal** [comment]
One think with the images is that they are as wide or wider than the text, which I find too imposing/loud almost intimidating (the mac effect :tongue: ). Can we have some padding (maybe 20-30 pixels) from both sides? I'm not sure if markdown can do that but is OK to add some html code there to have a distinct segment for the images.

**Comment by 01micko** [comment]
`<p style="padding:40px;">![Screenshot of Tahrpup 6.0.5](screenshots/tahr.jpg)</p>`

That works. Might apply the same to the front page.

> Looks nice though I would probably had the "advantages" first and then after the "read on" and to keep/start the cheeky mood, add the image under the title "Yes, but what does it look like?

Food for thought.

**Comment by mavrothal** [comment]
Nicer :+1:
